name: yearly_checkboxes

on:
  schedule:
    - cron: '0 0 1 1 *'  # 00:00 UTC on Jan 1 every year
  workflow_dispatch:     # Allow manual trigger

jobs:
  generate_yearly_checkboxes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run yearly checkboxes script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python yearly_checkboxes.py
